import type {
  ExecutionRun,
  TaskDefinition,
  GitCommit,
  LessonLearned,
} from "@ai-workbench/shared";

export function generateReadme(params: {
  run: ExecutionRun;
  tasks: TaskDefinition[];
  commits: GitCommit[];
  lessons: LessonLearned[];
  report: string;
  totalCost: number;
}): string {
  const { run, tasks, commits, lessons, report, totalCost } = params;
  const completed = tasks.filter((t) => t.status === "completed");
  const failed = tasks.filter((t) => t.status === "failed");
  const dirName = run.workingDir.split("/").pop() || "project";

  const lines: string[] = [];
  lines.push(`# ${dirName}`);
  lines.push("");

  if (run.goals.length > 0) {
    lines.push("## Goals");
    lines.push("");
    for (const g of run.goals) lines.push(`- ${g}`);
    lines.push("");
  }

  if (report) {
    lines.push("## Summary");
    lines.push("", report, "");
  }

  lines.push("## Tasks Completed");
  lines.push("");
  lines.push("| # | Task | Score | Duration |");
  lines.push("|---|------|-------|----------|");
  completed.forEach((t, i) => {
    const dur = t.durationMs ? fmtDur(t.durationMs) : "-";
    const score = t.score != null ? `${(t.score * 100).toFixed(0)}%` : "-";
    lines.push(`| ${i + 1} | ${trunc(t.content, 60)} | ${score} | ${dur} |`);
  });

  if (failed.length > 0) {
    lines.push("", "### Failed Tasks", "");
    for (const t of failed) lines.push(`- ${trunc(t.content, 80)}`);
    lines.push("");
  }

  if (commits.length > 0) {
    const files = new Set<string>();
    for (const c of commits) {
      if (c.filesChanged) for (const f of c.filesChanged) files.add(f);
    }
    if (files.size > 0) {
      lines.push("## Files Modified", "");
      for (const f of Array.from(files).sort()) lines.push(`- \`${f}\``);
      lines.push("");
    }
    lines.push("## Commit History", "");
    for (const c of commits) {
      const h = c.hash?.substring(0, 7) || "?";
      const ai = c.isAiCommit ? " [AI]" : "";
      lines.push(`- \`${h}\`${ai} ${c.message}`);
    }
    lines.push("");
  }

  if (lessons.length > 0) {
    lines.push("## Lessons Learned", "");
    for (const l of lessons) {
      const tag = l.category === "success" ? "+" : l.category === "failure" ? "-" : "~";
      lines.push(`- ${tag} ${l.lesson}`);
    }
    lines.push("");
  }

  lines.push("## Statistics", "");
  lines.push(`- **Total tasks**: ${tasks.length}`);
  lines.push(`- **Completed**: ${completed.length}`);
  lines.push(`- **Failed**: ${failed.length}`);
  lines.push(`- **Commits**: ${commits.length}`);
  lines.push(`- **Total cost**: $${totalCost.toFixed(4)}`);
  if (run.startedAt) lines.push(`- **Started**: ${new Date(run.startedAt).toISOString()}`);
  if (run.completedAt) lines.push(`- **Completed**: ${new Date(run.completedAt).toISOString()}`);
  lines.push("");
  lines.push("---");
  lines.push(`*Generated by AI Task Workbench at ${new Date().toISOString()}*`);

  return lines.join("\n");
}

function trunc(s: string, n: number): string {
  return s.length <= n ? s : s.substring(0, n - 3) + "...";
}

function fmtDur(ms: number): string {
  const s = Math.floor(ms / 1000);
  if (s < 60) return `${s}s`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m ${s % 60}s`;
  return `${Math.floor(m / 60)}h ${m % 60}m`;
}
